// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8ooVWEe1Q61s6LId4aAhy63dKy-XeL0',
    appId: '1:333209496476:web:e380fa2f269a4004e87659',
    messagingSenderId: '333209496476',
    projectId: 'womansafety-215e2',
    authDomain: 'womansafety-215e2.firebaseapp.com',
    databaseURL: 'https://womansafety-215e2-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-215e2.firebasestorage.app',
    measurementId: 'G-BSS4ZRB21Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9U3Z7yVQkv0euyHCN57G83gR3gUICo4I',
    appId: '1:333209496476:android:6d2fca5c4eacfe05e87659',
    messagingSenderId: '333209496476',
    projectId: 'womansafety-215e2',
    databaseURL: 'https://womansafety-215e2-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-215e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYgyv7JB7P5qaOaMbmY0m7NLb58_t48k',
    appId: '1:333209496476:ios:d1ab5ed3cd946ba0e87659',
    messagingSenderId: '333209496476',
    projectId: 'womansafety-215e2',
    databaseURL: 'https://womansafety-215e2-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-215e2.firebasestorage.app',
    iosBundleId: 'com.safelife.safelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGYgyv7JB7P5qaOaMbmY0m7NLb58_t48k',
    appId: '1:333209496476:ios:d1ab5ed3cd946ba0e87659',
    messagingSenderId: '333209496476',
    projectId: 'womansafety-215e2',
    databaseURL: 'https://womansafety-215e2-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-215e2.firebasestorage.app',
    iosBundleId: 'com.safelife.safelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8ooVWEe1Q61s6LId4aAhy63dKy-XeL0',
    appId: '1:333209496476:web:7f8772e70a782c34e87659',
    messagingSenderId: '333209496476',
    projectId: 'womansafety-215e2',
    authDomain: 'womansafety-215e2.firebaseapp.com',
    databaseURL: 'https://womansafety-215e2-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-215e2.firebasestorage.app',
    measurementId: 'G-DHFDNVXQ0B',
  );
}
